import streamlit as st
import pandas as pd
import plotly.express as px
import os

st.set_page_config(page_title="Seed Breeder Assessment Tool", layout="wide")

@st.cache_data
def load_data():
    # Target the exact folder and files generated by your scoring_engine.py
    output_dir = './scoring_outputs' 
    
    try:
        rankings = pd.read_csv(f'{output_dir}/hybrid_rankings.csv')
        gxe = pd.read_csv(f'{output_dir}/gxe_matrix.csv')
        tp_rankings = pd.read_csv(f'{output_dir}/timepoint_rankings.csv')
    except FileNotFoundError:
        st.error(f"⚠️ Could not find CSVs in {output_dir}/. Run scoring_engine.py first to generate them.")
        st.stop()
        
    return rankings, gxe, tp_rankings

rankings, gxe_matrix, tp_rankings = load_data()

# ─────────────────────────────────────────────
# SIDEBAR FILTERS
# ─────────────────────────────────────────────
st.sidebar.header("Filter Pipeline")

# Dynamically grab the locations/environments from the GxE matrix columns
environments = [c for c in gxe_matrix.columns if c != 'genotype']
selected_envs = st.sidebar.multiselect("Select Environments", environments, default=environments)

top_n = st.sidebar.slider("Top N Hybrids to Display", 5, len(rankings), 10)
filtered_rankings = rankings.head(top_n)

# ─────────────────────────────────────────────
# MAIN LAYOUT
# ─────────────────────────────────────────────
st.title("🌱 Seed Breeder Assessment Dashboard")
st.markdown("Identify stable, high-yielding commercial candidates and cull underperformers early.")

# --- SECTION 1: The Ranker (Leaderboard) ---
st.subheader("1. Hybrid Ranker (Top Candidates)")
display_df = filtered_rankings[['genotype', 'predicted_yield_mean', 'predicted_yield_std', 'breeder_score', 'yield_tier', 'stability_tier']].copy()

st.dataframe(
    display_df.set_index('genotype'),
    use_container_width=True,
    column_config={
        "predicted_yield_mean": st.column_config.NumberColumn("Mean Yield (bu/ac)", format="%.1f 🌽"),
        "predicted_yield_std": st.column_config.ProgressColumn("Stability (Std Dev)", min_value=0, max_value=float(rankings['predicted_yield_std'].max())),
        "breeder_score": st.column_config.NumberColumn("Breeder Score", format="%.3f")
    }
)

col1, col2 = st.columns(2)

# --- SECTION 2: Yield vs. Stability Scatter ---
with col1:
    st.subheader("2. Performance vs. Stability")
    st.markdown("Ideal hybrids sit in the **bottom right** (High Yield, Low Variance).")
    
    fig_scatter = px.scatter(
        filtered_rankings, 
        x='predicted_yield_mean', 
        y='predicted_yield_std', 
        text='genotype',
        labels={'predicted_yield_mean': 'Mean Predicted Yield', 'predicted_yield_std': 'Yield Variance (Instability)'},
        color='predicted_yield_std',
        color_continuous_scale='RdYlGn_r'
    )
    # Push the text labels above the dots so they don't overlap
    fig_scatter.update_traces(textposition='top center', marker=dict(size=12, line=dict(width=1, color='DarkSlateGrey')))
    st.plotly_chart(fig_scatter, use_container_width=True)

# --- SECTION 3: Time Series ---
with col2:
    st.subheader("3. Mid-Season Growth Trajectory")
    st.markdown("Tracking predicted yield stability over timepoints.")
    
    # Melt the wide timepoint pivot table into a long format for Plotly
    ts_long = tp_rankings[tp_rankings['genotype'].isin(filtered_rankings['genotype'])].melt(
        id_vars='genotype', 
        var_name='timepoint', 
        value_name='predicted_yield'
    )
    # Clean up the X-axis labels (e.g., changes "predicted_yield_TP1" -> "TP1")
    ts_long['timepoint'] = ts_long['timepoint'].str.replace('predicted_yield_', '')
    
    fig_ts = px.line(
        ts_long, 
        x='timepoint', 
        y='predicted_yield', 
        color='genotype', 
        markers=True,
        labels={'predicted_yield': 'Predicted Yield', 'timepoint': 'Timepoint'}
    )
    st.plotly_chart(fig_ts, use_container_width=True)

# --- SECTION 4: GxE Heatmap ---
st.subheader("4. GxE Interaction Matrix")
st.markdown("Visualizing which hybrids are robust across all environments vs. highly specialized.")

# Filter the matrix for the top N genotypes and the sidebar-selected environments
gxe_filtered = gxe_matrix[gxe_matrix['genotype'].isin(filtered_rankings['genotype'])].set_index('genotype')
gxe_filtered = gxe_filtered[selected_envs]

fig_heat = px.imshow(
    gxe_filtered, 
    labels=dict(x="Environment", y="Genotype", color="Predicted Yield"),
    x=gxe_filtered.columns,
    y=gxe_filtered.index,
    color_continuous_scale='Viridis',
    aspect="auto"
)
st.plotly_chart(fig_heat, use_container_width=True)