import streamlit as st
import pandas as pd
import plotly.express as px
import os
import run_inference

st.set_page_config(page_title="Seed Breeder Assessment Tool", layout="wide")

@st.cache_data
def load_data():
    # Target the exact folder and files generated by your scoring_engine.py
    output_dir = './scoring_outputs' 
    
    try:
        rankings = pd.read_csv(f'{output_dir}/hybrid_rankings.csv')
        gxe = pd.read_csv(f'{output_dir}/gxe_matrix.csv')
        tp_rankings = pd.read_csv(f'{output_dir}/timepoint_rankings.csv')
    except FileNotFoundError:
        # Provide empty dataframes so the UI doesn't crash on first load
        return pd.DataFrame(), pd.DataFrame(), pd.DataFrame()
        
    return rankings, gxe, tp_rankings

rankings, gxe_matrix, tp_rankings = load_data()

# ─────────────────────────────────────────────
# SIDEBAR FILTERS & INFERENCE
# ─────────────────────────────────────────────
st.sidebar.header("1. Upload New Data")
uploaded_zip = st.sidebar.file_uploader("Upload Drone ZIP", type="zip")
uploaded_csv = st.sidebar.file_uploader("Upload Planting CSV", type="csv")

if st.sidebar.button("Run Predictions"):
    if uploaded_zip and uploaded_csv:
        # Save temporary files for the pipeline to read
        temp_zip_path = "temp_upload.zip"
        temp_csv_path = "temp_metadata.csv"
        
        with open(temp_zip_path, "wb") as f:
            f.write(uploaded_zip.getbuffer())
        with open(temp_csv_path, "wb") as f:
            f.write(uploaded_csv.getbuffer())
            
        with st.spinner("Processing imagery and predicting yield..."):
            # Uses your specialized 2022 pre-trained model
            run_inference.process_zip_upload(temp_zip_path, temp_csv_path, 'best_model.pkl')
            st.sidebar.success("Analysis Complete!")
            st.cache_data.clear() # Forces the dashboard to reload the new CSVs
            st.rerun()
    else:
        st.sidebar.error("Please upload both files first.")

st.sidebar.divider()
st.sidebar.header("Dashboard Filters")

if not gxe_matrix.empty:
    # 1. Drop any 'Unnamed' columns that shouldn't be there
    clean_cols = [c for c in gxe_matrix.columns if not c.startswith('Unnamed')]
    
    # 2. Grab only the columns that represent actual locations
    # (Exclude 'genotype' and any metadata)
    environments = [c for c in clean_cols if c not in ['genotype', 'breeder_score', 'yield_tier']]
    
    selected_envs = st.sidebar.multiselect("Select Environments", environments, default=environments)
    
    if not rankings.empty:
        top_n = st.sidebar.slider("Top Hybrids to Display", 5, len(rankings), 10)
        filtered_rankings = rankings.head(top_n)
else:
    st.sidebar.info("Run predictions to enable filters.")

# ─────────────────────────────────────────────
# MAIN LAYOUT
# ─────────────────────────────────────────────
st.title("Seed Breeder Assessment Dashboard")

if rankings.empty:
    st.warning("No prediction data found. Upload drone imagery and a planting plan in the sidebar to begin.")
    st.stop()

# --- SECTION 1: The Ranker (Leaderboard) ---
st.subheader("Hybrid Ranker")

# 1. Update display columns to use our new percentage
target_cols = ['genotype', 'predicted_yield_mean', 'stability_pct', 'breeder_score', 'yield_tier', 'stability_tier']
available_cols = [c for c in target_cols if c in filtered_rankings.columns]
display_df = filtered_rankings[available_cols].copy()

st.dataframe(
    display_df.set_index('genotype'),
    width='stretch', 
    column_config={
        "predicted_yield_mean": st.column_config.NumberColumn("Mean Yield (bu/ac)", format="%.1f"),
        "stability_pct": st.column_config.ProgressColumn(
            "Stability Index", 
            help="100% means perfectly consistent performance across all drone flights.",
            format="%.0f%%", # This turns 0.85 into 85%
            min_value=0, 
            max_value=1
        ),
        "breeder_score": st.column_config.NumberColumn("Breeder Score", format="%.3f")
    }
)

# --- SECTION 2: Yield vs. Stability Scatter ---
st.subheader("Performance vs. Stability")

fig_scatter = px.scatter(
    filtered_rankings,
    x='predicted_yield_mean',
    y='predicted_yield_std',
    text='genotype',
    color='predicted_yield_std',
    color_continuous_scale='RdYlGn_r',
    labels={'predicted_yield_mean': 'Mean Predicted Yield', 'predicted_yield_std': 'Yield Variance (Instability)'}
)

# Use width='stretch' to ensure it takes up the full row
st.plotly_chart(fig_scatter, width='stretch')


# --- SECTION 3: Mid-Season Growth Trajectory ---
st.subheader("Growth Trajectory")

if 'genotype' in tp_rankings.columns and not filtered_rankings.empty:
    # 1. Melt the wide timepoint data
    ts_long = tp_rankings[tp_rankings['genotype'].isin(filtered_rankings['genotype'])].melt(
        id_vars='genotype', 
        var_name='timepoint', 
        value_name='predicted_yield'
    )
    ts_long['timepoint'] = ts_long['timepoint'].str.replace('predicted_yield_', '')

    # 2. Rank-Based Color Map Logic
    num_hybrids = len(filtered_rankings)
    colors = px.colors.sample_colorscale(
        "RdYlGn_r", 
        [i/(num_hybrids - 1) if num_hybrids > 1 else 0 for i in range(num_hybrids)]
    )
    
    color_map = {
        row['genotype']: colors[i] 
        for i, row in enumerate(filtered_rankings.to_dict('records'))
    }

    # 3. Plot using the full width
    fig_ts = px.line(
        ts_long, 
        x='timepoint', 
        y='predicted_yield', 
        color='genotype',
        color_discrete_map=color_map,
        markers=True,
        labels={'predicted_yield': 'Predicted Yield', 'timepoint': 'Timepoint'}
    )
    
    st.plotly_chart(fig_ts, width='stretch')
else:
    st.info("Timepoint data will appear here once genotypes are processed.")

# --- SECTION 4: GxE Heatmap ---
st.subheader("GxE Interaction Matrix")
gxe_filtered = gxe_matrix[gxe_matrix['genotype'].isin(filtered_rankings['genotype'])].set_index('genotype')

if not gxe_filtered.empty and selected_envs:
    gxe_display = gxe_filtered[selected_envs]
    fig_heat = px.imshow(
        gxe_display, 
        aspect="auto", 
        color_continuous_scale='YlGn',
        labels=dict(x="Environment", y="Genotype", color="Yield")
    )
    st.plotly_chart(fig_heat, width='stretch')